/**
 * Read Amazon's own FBA box label.
 *
 * This is the SHIPPED side of reconciliation. The inventory ledger says what
 * Amazon received; nothing in the reports a seller can reach says what the
 * seller actually sent, because that lives behind the Fulfillment API role.
 * The box labels do — they are generated by Amazon, printed by the seller, and
 * carry the shipment id, destination, SKU and quantity per box.
 *
 * Recognition (document-recognize) decides a file IS a box label. This module
 * reads the values out of one. Kept separate so a change to what a label says
 * cannot alter what counts as a label.
 */

export type FbaBoxLabel = {
  /** Amazon shipment id, e.g. FBA19CBC1Q88. The join key to ledger Receipts. */
  shipmentId?: string;
  boxNumber?: number;
  boxCount?: number;
  /** Destination fulfillment centre, e.g. LBE1. */
  destinationFc?: string;
  /** Present only on single-SKU boxes; see `singleSku`. */
  sku?: string;
  quantity?: number;
  /** ISO date, normalised from the label's "Exp Nov 30, 2026" form. */
  expiresOn?: string;
  weightLb?: number;
  createdAt?: string;
  shipToName?: string;
  /**
   * The printed street address of the destination FC, line by line. The label
   * is the one document a seller always has that states an FC's address, so
   * this is what seeds the FC address book without anyone typing.
   */
  shipToAddressLines?: string[];
  /**
   * Amazon prints "Single SKU" when a box holds one SKU. A mixed box lists its
   * contents in a form this parser does not attempt, so quantity is left unset
   * rather than guessed.
   */
  singleSku: boolean;
  /** What could not be read, so a partial label is usable and honest. */
  warnings: string[];
};

const MONTHS: Record<string, string> = {
  jan: '01',
  feb: '02',
  mar: '03',
  apr: '04',
  may: '05',
  jun: '06',
  jul: '07',
  aug: '08',
  sep: '09',
  oct: '10',
  nov: '11',
  dec: '12',
};

/**
 * Box ids are the shipment id, the letter U, then a six-digit box sequence:
 * FBA19G33WPZ3 + U + 000001. Shipment ids are FBA plus nine characters, which
 * holds across every id seen in real ledger exports.
 */
const BOX_ID = /\b(FBA[0-9A-Z]{9})U(\d{6})\b/;
const BARE_SHIPMENT_ID = /\b(FBA[0-9A-Z]{9})\b/;
/** Fulfillment centre codes are three letters and a digit: LBE1, SMF1, ACY1. */
const FC_CODE = /\b([A-Z]{3}\d)\b/;

function toIsoDate(
  month: string,
  day: string,
  year: string
): string | undefined {
  const mm = MONTHS[month.slice(0, 3).toLowerCase()];
  if (!mm) return undefined;
  return `${year}-${mm}-${day.padStart(2, '0')}`;
}

export function parseFbaBoxLabel(text: string): FbaBoxLabel {
  const warnings: string[] = [];
  const flat = text.replace(/\s+/g, ' ').trim();
  const label: FbaBoxLabel = { singleSku: /single sku/i.test(flat), warnings };

  const boxId = flat.match(BOX_ID);
  if (boxId) {
    label.shipmentId = boxId[1];
    label.boxNumber = Number(boxId[2]);
  } else {
    const bare = flat.match(BARE_SHIPMENT_ID);
    if (bare) label.shipmentId = bare[1];
    else warnings.push('no FBA shipment id found');
  }

  const boxOf = flat.match(/FBA Box (\d+) of (\d+)/i);
  if (boxOf) {
    // Prefer the printed "1 of 3" over the box id sequence: it also gives the
    // total, which is what says whether a set of labels is complete.
    label.boxNumber = Number(boxOf[1]);
    label.boxCount = Number(boxOf[2]);
  } else {
    warnings.push('no "Box N of M" found — cannot tell if the set is complete');
  }

  // Read the FC from the ship-to block only. A three-letter-plus-digit token
  // elsewhere on the label (a street number, a lot code) would otherwise win.
  const shipTo = flat.match(/SHIP TO:(.*?)(?:Created:|$)/i)?.[1] ?? '';
  const fc = shipTo.match(FC_CODE);
  if (fc) label.destinationFc = fc[1];
  else warnings.push('no destination fulfillment centre found');

  const shipToName = shipTo.match(/(FBA:\s*[^0-9]+?)(?=\s+[A-Z]{3}\d\b|\s+\d)/);
  if (shipToName) label.shipToName = shipToName[1].trim();

  // The street address, from the UN-flattened text so line structure survives.
  // Everything in the ship-to block that is not the "FBA: ..." name and not
  // the bare FC code is address. Falls back to one joined line when the
  // extractor returned no line breaks.
  const rawShipTo =
    text.match(/SHIP TO:?([\s\S]*?)(?:Created:|FBA Box|$)/i)?.[1] ?? '';
  const addressLines = rawShipTo
    .split(/\n+/)
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => !/^FBA:/i.test(line))
    .filter((line) => !/^[A-Z]{3}\d$/.test(line));
  if (addressLines.length > 1) {
    label.shipToAddressLines = addressLines;
  } else {
    const flatAddress = shipTo
      .replace(/FBA:\s*[^0-9]+?(?=\s+[A-Z]{3}\d\b|\s+\d)/, '')
      .replace(FC_CODE, '')
      .trim();
    if (flatAddress) label.shipToAddressLines = [flatAddress];
  }

  if (label.singleSku) {
    const sku = flat.match(/Single SKU\s+([A-Za-z0-9][A-Za-z0-9._-]{2,})/i);
    if (sku) label.sku = sku[1];
    else warnings.push('single-SKU box but no SKU could be read');

    const qty = flat.match(/\bQty\s+(\d+)\b/i);
    if (qty) label.quantity = Number(qty[1]);
    else warnings.push('single-SKU box but no quantity could be read');
  } else {
    warnings.push('mixed-SKU box — contents not parsed, quantity unknown');
  }

  const exp = flat.match(/\bExp\s+([A-Za-z]{3,})\s+(\d{1,2}),?\s*(\d{4})/i);
  if (exp) {
    const iso = toIsoDate(exp[1], exp[2], exp[3]);
    if (iso) label.expiresOn = iso;
  }

  const weight = flat.match(/(\d+(?:\.\d+)?)\s*lbs?\b/i);
  if (weight) label.weightLb = Number(weight[1]);

  const created = flat.match(/Created:\s*(\d{4}\/\d{2}\/\d{2}\s+\d{2}:\d{2})/);
  if (created) label.createdAt = created[1];

  return label;
}

/**
 * Parse a label sheet, one label per page.
 *
 * Amazon prints every box of a shipment into a single PDF. Parsing the joined
 * text finds only the first label, because each pattern matches once: a real
 * four-box sheet came back as "box 1 of 4, 40 units" and the other three boxes
 * were silently discarded, halving the shipped quantity.
 *
 * Pages with no shipment id are dropped rather than reported — a cover sheet or
 * a blank page is not a missing box.
 */
export function parseFbaBoxLabels(pages: string[]): FbaBoxLabel[] {
  return pages
    .map((page) => parseFbaBoxLabel(page))
    .filter((label) => label.shipmentId);
}

export type ShipmentFromLabels = {
  shipmentId: string;
  destinationFc?: string;
  /** Distinct boxes read, after discarding repeats of the same box number. */
  boxesSeen: number;
  /** From "Box N of M", when the labels said so. */
  boxesDeclared?: number;
  /**
   * True only when every declared box has been seen. Quantities from an
   * incomplete set understate what was shipped, and saying so is the difference
   * between a usable figure and a misleading one.
   */
  complete: boolean;
  units: Array<{ sku: string; quantity: number; boxes: number }>;
  totalUnits: number;
  warnings: string[];
};

/**
 * Roll a pile of box labels up into what was shipped, per shipment.
 *
 * Deduplicates on (shipmentId, boxNumber) so re-uploading the same label — or
 * printing two copies of it — cannot inflate the shipped quantity.
 */
export function summariseBoxLabels(
  labels: FbaBoxLabel[]
): ShipmentFromLabels[] {
  const byShipment = new Map<string, FbaBoxLabel[]>();
  for (const label of labels) {
    if (!label.shipmentId) continue;
    const list = byShipment.get(label.shipmentId) ?? [];
    list.push(label);
    byShipment.set(label.shipmentId, list);
  }

  return [...byShipment.entries()].map(([shipmentId, all]) => {
    const seen = new Map<string, FbaBoxLabel>();
    for (const label of all) {
      // Labels with no box number cannot be deduplicated against each other, so
      // keep them apart by position rather than collapsing them into one.
      const key =
        label.boxNumber != null ? `#${label.boxNumber}` : `?${seen.size}`;
      if (!seen.has(key)) seen.set(key, label);
    }
    const boxes = [...seen.values()];
    const declared = boxes.find((b) => b.boxCount != null)?.boxCount;

    const bySku = new Map<string, { quantity: number; boxes: number }>();
    const warnings: string[] = [];
    for (const box of boxes) {
      if (!box.singleSku) {
        warnings.push(
          `box ${
            box.boxNumber ?? '?'
          } is mixed-SKU and its units are not counted`
        );
        continue;
      }
      if (!box.sku || box.quantity == null) {
        warnings.push(
          `box ${box.boxNumber ?? '?'} is missing its SKU or quantity`
        );
        continue;
      }
      const entry = bySku.get(box.sku) ?? { quantity: 0, boxes: 0 };
      entry.quantity += box.quantity;
      entry.boxes += 1;
      bySku.set(box.sku, entry);
    }

    const complete = declared != null && boxes.length >= declared;
    if (declared != null && boxes.length < declared) {
      warnings.push(
        `only ${boxes.length} of ${declared} box labels — the shipped total is a floor, not a count`
      );
    }
    if (declared == null) {
      warnings.push(
        'no box label declared a total, so completeness is unknown'
      );
    }

    const units = [...bySku.entries()].map(([sku, v]) => ({ sku, ...v }));
    return {
      shipmentId,
      destinationFc: boxes.find((b) => b.destinationFc)?.destinationFc,
      boxesSeen: boxes.length,
      boxesDeclared: declared,
      complete,
      units,
      totalUnits: units.reduce((total, u) => total + u.quantity, 0),
      warnings,
    };
  });
}
