/**
 * Settlement reports, which behave unlike every other kind in the registry.
 *
 * Amazon produces them on its own settlement cycle and `createReport` rejects
 * the type outright, so they can only be listed and downloaded. A date range
 * spans several of them rather than one, and roughly 90 days are retained —
 * after which the data is gone, which is the whole reason for archiving.
 *
 * The failures worth guarding are quiet ones: a second header row parsed as
 * data, or the sync path silently calling the request API for a type that
 * cannot be requested.
 */

import { describe, expect, it, vi } from 'vitest';
import { detectReportKind, parseReport } from './report-ingest.js';
import { REPORTS } from './report-registry.js';

/** Trimmed and scrubbed shape of Amazon's V2 flat file. */
const SETTLEMENT_HEADER =
  'settlement-id\tsettlement-start-date\tsettlement-end-date\tdeposit-date\t' +
  'total-amount\tcurrency\ttransaction-type\torder-id\tadjustment-id\t' +
  'marketplace-name\tamount-type\tamount-description\tamount\tposted-date\t' +
  'sku\tquantity-purchased';

/** The totals row: settlement-level amounts, every transaction column empty. */
const TOTALS_ROW =
  '90210\t2026-07-01\t2026-07-15\t2026-07-17\t1420.55\tUSD\t\t\t\t\t\t\t\t\t\t';

function transactionRow(
  amountType: string,
  description: string,
  amount: string,
  sku = 'SKU-1'
): string {
  return (
    `90210\t2026-07-01\t2026-07-15\t2026-07-17\t\tUSD\tOrder\t111-2223334-5556667\t\t` +
    `amazon.com\t${amountType}\t${description}\t${amount}\t2026-07-08\t${sku}\t1`
  );
}

const FILE_ONE = [
  SETTLEMENT_HEADER,
  TOTALS_ROW,
  transactionRow('ItemPrice', 'Principal', '29.99'),
  transactionRow('ItemFees', 'Commission', '-4.50'),
].join('\n');

const FILE_TWO = [
  SETTLEMENT_HEADER,
  '90211\t2026-07-16\t2026-07-31\t2026-08-02\t980.10\tUSD\t\t\t\t\t\t\t\t\t\t',
  transactionRow('ItemFees', 'FBAPerUnitFulfillmentFee', '-3.22', 'SKU-2'),
].join('\n');

describe('settlement registry entry', () => {
  it('is marked auto-generated, because it cannot be requested', () => {
    // createReport REJECTS this type. Without the flag the sync path would call
    // runReport and fail on every attempt with an error about the report type
    // rather than about the request being impossible.
    expect(REPORTS.settlement.autoGenerated).toBe(true);
    expect(REPORTS.settlement.reportType).toBe(
      'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2'
    );
  });

  it('is the only kind that is auto-generated', () => {
    const flagged = Object.values(REPORTS)
      .filter((definition) => definition.autoGenerated)
      .map((definition) => definition.kind);

    expect(flagged).toEqual(['settlement']);
  });

  it('maps the two columns a fee analysis groups by', () => {
    // amountType is the family, amountDescription the specific line. Without
    // both, "what did FBA fees cost me" is unanswerable from stored rows.
    expect(REPORTS.settlement.fields.amountType).toContain('amounttype');
    expect(REPORTS.settlement.fields.amountDescription).toContain(
      'amountdescription'
    );
  });
});

describe('settlement parsing', () => {
  it('is identified from its headers', () => {
    const detection = detectReportKind(FILE_ONE);

    expect(detection?.kind).toBe('settlement');
  });

  it('keeps fee rows distinguishable from item price rows', () => {
    const parsed = parseReport({
      kind: 'settlement',
      sellerId: 'SELLER1',
      text: FILE_ONE,
    });
    const descriptions = parsed.rows.map((row) => row.fields.amountDescription);

    expect(descriptions).toContain('Principal');
    expect(descriptions).toContain('Commission');
  });

  it('reads the settlement id onto every row, not just the totals row', () => {
    // Rows are grouped by settlement; a row that lost its settlementId cannot
    // be reconciled against the deposit it belongs to.
    const parsed = parseReport({
      kind: 'settlement',
      sellerId: 'SELLER1',
      text: FILE_ONE,
    });

    expect(parsed.rows.length).toBeGreaterThan(0);
    for (const row of parsed.rows) {
      expect(row.fields.settlementId).toBe('90210');
    }
  });
});

/**
 * Concatenation. A window covers several settlements, so the sync path stitches
 * their files together — and only the first may keep its header.
 */
function stripHeaderRow(text: string): string {
  const newline = text.indexOf('\n');
  return newline === -1 ? '' : text.slice(newline + 1);
}

describe('stitching several settlement files together', () => {
  it('parses rows from every file in the window', () => {
    const combined = [FILE_ONE, stripHeaderRow(FILE_TWO)].join('\n');
    const parsed = parseReport({
      kind: 'settlement',
      sellerId: 'SELLER1',
      text: combined,
    });
    const settlements = new Set(
      parsed.rows.map((row) => row.fields.settlementId)
    );

    expect(settlements).toEqual(new Set(['90210', '90211']));
  });

  it('does not parse the second file header as a data row', () => {
    // The failure this guards: leaving both headers in produces a row whose
    // every field is a column name — plausible-looking rows that poison any
    // aggregate built on them, and nothing throws.
    const combined = [FILE_ONE, stripHeaderRow(FILE_TWO)].join('\n');
    const parsed = parseReport({
      kind: 'settlement',
      sellerId: 'SELLER1',
      text: combined,
    });

    for (const row of parsed.rows) {
      expect(row.fields.settlementId).not.toBe('settlement-id');
      expect(row.fields.amountType).not.toBe('amount-type');
    }
  });

  it('would corrupt the data if the header were left in', () => {
    // Proving the guard above tests something real: without the strip, a row
    // made entirely of column names appears.
    const naive = [FILE_ONE, FILE_TWO].join('\n');
    const parsed = parseReport({
      kind: 'settlement',
      sellerId: 'SELLER1',
      text: naive,
    });

    expect(
      parsed.rows.some((row) => row.fields.settlementId === 'settlement-id')
    ).toBe(true);
  });
});

describe('fetching auto-generated reports', () => {
  it('lists rather than requests, and widens the window past the range', async () => {
    // createdSince/createdUntil filter on when Amazon PUBLISHED a report, which
    // lags the period it covers by days. Asking precisely for the requested
    // range silently misses the most recent settlement every single time.
    const listReports = vi.fn().mockResolvedValue({ reports: [] });
    const runReport = vi.fn();

    const { syncReport } = await import('./report-sync.js');
    const result = await syncReport({
      client: { listReports, runReport } as never,
      sellerId: 'A2HXBWIE3KMLKV',
      kind: 'settlement',
      from: '2026-07-01T00:00:00.000Z',
      to: '2026-07-31T00:00:00.000Z',
    });

    expect(runReport).not.toHaveBeenCalled();
    expect(listReports).toHaveBeenCalledOnce();

    const call = listReports.mock.calls[0][0];
    expect(call.reportTypes).toEqual([
      'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2',
    ]);
    expect(new Date(call.createdUntil).getTime()).toBeGreaterThan(
      new Date('2026-07-31T00:00:00.000Z').getTime()
    );

    // No reports in the window is a real outcome, not a crash: it means Amazon
    // has not settled in that period, or the 90-day retention has passed.
    expect('error' in result).toBe(true);
  });
});
