/**
 * Settlement reports, which behave unlike every other kind in the registry.
 *
 * Amazon produces them on its own settlement cycle and `createReport` rejects
 * the type outright, so they can only be listed and downloaded. A date range
 * spans several of them rather than one, and roughly 90 days are retained —
 * after which the data is gone, which is the whole reason for archiving.
 *
 * The failures worth guarding are quiet ones: a second header row parsed as
 * data, or the sync path silently calling the request API for a type that
 * cannot be requested.
 */

import { describe, expect, it, vi } from 'vitest';
import { detectReportKind, parseReport } from './report-ingest.js';
import { REPORTS } from './report-registry.js';
import {
  collectKnownSkus,
  economicRows,
  isPassThroughTax,
  passThroughTaxResidual,
  reconcileSettlements,
  resolveSku,
} from './settlement-report.js';

/** Trimmed and scrubbed shape of Amazon's V2 flat file. */
const SETTLEMENT_HEADER =
  'settlement-id\tsettlement-start-date\tsettlement-end-date\tdeposit-date\t' +
  'total-amount\tcurrency\ttransaction-type\torder-id\tadjustment-id\t' +
  'marketplace-name\tamount-type\tamount-description\tamount\tposted-date\t' +
  'sku\tquantity-purchased';

/** The totals row: settlement-level amounts, every transaction column empty. */
const TOTALS_ROW =
  '90210\t2026-07-01\t2026-07-15\t2026-07-17\t1420.55\tUSD\t\t\t\t\t\t\t\t\t\t';

function transactionRow(
  amountType: string,
  description: string,
  amount: string,
  sku = 'SKU-1'
): string {
  return (
    `90210\t2026-07-01\t2026-07-15\t2026-07-17\t\tUSD\tOrder\t111-2223334-5556667\t\t` +
    `amazon.com\t${amountType}\t${description}\t${amount}\t2026-07-08\t${sku}\t1`
  );
}

const FILE_ONE = [
  SETTLEMENT_HEADER,
  TOTALS_ROW,
  transactionRow('ItemPrice', 'Principal', '29.99'),
  transactionRow('ItemFees', 'Commission', '-4.50'),
].join('\n');

const FILE_TWO = [
  SETTLEMENT_HEADER,
  '90211\t2026-07-16\t2026-07-31\t2026-08-02\t980.10\tUSD\t\t\t\t\t\t\t\t\t\t',
  transactionRow('ItemFees', 'FBAPerUnitFulfillmentFee', '-3.22', 'SKU-2'),
].join('\n');

describe('settlement registry entry', () => {
  it('is marked auto-generated, because it cannot be requested', () => {
    // createReport REJECTS this type. Without the flag the sync path would call
    // runReport and fail on every attempt with an error about the report type
    // rather than about the request being impossible.
    expect(REPORTS.settlement.autoGenerated).toBe(true);
    expect(REPORTS.settlement.reportType).toBe(
      'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2'
    );
  });

  it('is the only kind that is auto-generated', () => {
    const flagged = Object.values(REPORTS)
      .filter((definition) => definition.autoGenerated)
      .map((definition) => definition.kind);

    expect(flagged).toEqual(['settlement']);
  });

  it('maps the two columns a fee analysis groups by', () => {
    // amountType is the family, amountDescription the specific line. Without
    // both, "what did FBA fees cost me" is unanswerable from stored rows.
    expect(REPORTS.settlement.fields.amountType).toContain('amounttype');
    expect(REPORTS.settlement.fields.amountDescription).toContain(
      'amountdescription'
    );
  });
});

describe('settlement parsing', () => {
  it('is identified from its headers', () => {
    const detection = detectReportKind(FILE_ONE);

    expect(detection?.kind).toBe('settlement');
  });

  it('keeps fee rows distinguishable from item price rows', () => {
    const parsed = parseReport({
      kind: 'settlement',
      sellerId: 'SELLER1',
      text: FILE_ONE,
    });
    const descriptions = parsed.rows.map((row) => row.fields.amountDescription);

    expect(descriptions).toContain('Principal');
    expect(descriptions).toContain('Commission');
  });

  it('reads the settlement id onto every row, not just the totals row', () => {
    // Rows are grouped by settlement; a row that lost its settlementId cannot
    // be reconciled against the deposit it belongs to.
    const parsed = parseReport({
      kind: 'settlement',
      sellerId: 'SELLER1',
      text: FILE_ONE,
    });

    expect(parsed.rows.length).toBeGreaterThan(0);
    for (const row of parsed.rows) {
      expect(row.fields.settlementId).toBe('90210');
    }
  });
});

/**
 * Concatenation. A window covers several settlements, so the sync path stitches
 * their files together — and only the first may keep its header.
 */
function stripHeaderRow(text: string): string {
  const newline = text.indexOf('\n');
  return newline === -1 ? '' : text.slice(newline + 1);
}

describe('stitching several settlement files together', () => {
  it('parses rows from every file in the window', () => {
    const combined = [FILE_ONE, stripHeaderRow(FILE_TWO)].join('\n');
    const parsed = parseReport({
      kind: 'settlement',
      sellerId: 'SELLER1',
      text: combined,
    });
    const settlements = new Set(
      parsed.rows.map((row) => row.fields.settlementId)
    );

    expect(settlements).toEqual(new Set(['90210', '90211']));
  });

  it('does not parse the second file header as a data row', () => {
    // The failure this guards: leaving both headers in produces a row whose
    // every field is a column name — plausible-looking rows that poison any
    // aggregate built on them, and nothing throws.
    const combined = [FILE_ONE, stripHeaderRow(FILE_TWO)].join('\n');
    const parsed = parseReport({
      kind: 'settlement',
      sellerId: 'SELLER1',
      text: combined,
    });

    for (const row of parsed.rows) {
      expect(row.fields.settlementId).not.toBe('settlement-id');
      expect(row.fields.amountType).not.toBe('amount-type');
    }
  });

  it('would corrupt the data if the header were left in', () => {
    // Proving the guard above tests something real: without the strip, a row
    // made entirely of column names appears.
    const naive = [FILE_ONE, FILE_TWO].join('\n');
    const parsed = parseReport({
      kind: 'settlement',
      sellerId: 'SELLER1',
      text: naive,
    });

    expect(
      parsed.rows.some((row) => row.fields.settlementId === 'settlement-id')
    ).toBe(true);
  });
});

describe('fetching auto-generated reports', () => {
  it('lists rather than requests, and widens the window past the range', async () => {
    // createdSince/createdUntil filter on when Amazon PUBLISHED a report, which
    // lags the period it covers by days. Asking precisely for the requested
    // range silently misses the most recent settlement every single time.
    const listReports = vi.fn().mockResolvedValue({ reports: [] });
    const runReport = vi.fn();

    const { syncReport } = await import('./report-sync.js');
    const result = await syncReport({
      client: { listReports, runReport } as never,
      sellerId: 'A2HXBWIE3KMLKV',
      kind: 'settlement',
      from: '2026-07-01T00:00:00.000Z',
      to: '2026-07-31T00:00:00.000Z',
    });

    expect(runReport).not.toHaveBeenCalled();
    expect(listReports).toHaveBeenCalledOnce();

    const call = listReports.mock.calls[0][0];
    expect(call.reportTypes).toEqual([
      'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2',
    ]);
    expect(new Date(call.createdUntil).getTime()).toBeGreaterThan(
      new Date('2026-07-31T00:00:00.000Z').getTime()
    );

    // No reports in the window is a real outcome, not a crash: it means Amazon
    // has not settled in that period, or the 90-day retention has passed.
    expect('error' in result).toBe(true);
  });
});

/**
 * Reading a settlement, as opposed to parsing one.
 *
 * Every case below is a shape taken from real exports, because each of these
 * fails quietly: the wrong answer is a plausible number, not an exception.
 */

const parse = (text: string) =>
  parseReport({ kind: 'settlement', sellerId: 'seller-1', text }).rows;

describe('settlement reconciliation', () => {
  it('confirms the rows add up to the deposit Amazon declared', () => {
    // 1420.55 is the declared total, so the rows must reach exactly that.
    const text = [
      SETTLEMENT_HEADER,
      TOTALS_ROW,
      transactionRow('ItemPrice', 'Principal', '1425.05'),
      transactionRow('ItemFees', 'Commission', '-4.50'),
    ].join('\n');

    const [result] = reconcileSettlements(parse(text));
    expect(result.settlementId).toBe('90210');
    expect(result.declared).toBe(1420.55);
    expect(result.sum).toBe(1420.55);
    expect(result.balanced).toBe(true);
    // The totals row carries no `amount`, so it must not inflate the count.
    expect(result.rowCount).toBe(2);
  });

  it('reports a file that does not balance', () => {
    const text = [
      SETTLEMENT_HEADER,
      TOTALS_ROW,
      transactionRow('ItemPrice', 'Principal', '1000.00'),
    ].join('\n');

    const [result] = reconcileSettlements(parse(text));
    expect(result.balanced).toBe(false);
    expect(result.difference).toBe(-420.55);
  });

  it('says "unknown" rather than "unbalanced" when no total was declared', () => {
    // A truncated export with the header row lost. Claiming a discrepancy here
    // sends someone hunting for money that was never shown to be missing.
    const text = [
      SETTLEMENT_HEADER,
      transactionRow('ItemPrice', 'Principal', '29.99'),
    ].join('\n');

    const [result] = reconcileSettlements(parse(text));
    expect(result.declared).toBeNull();
    expect(result.balanced).toBeNull();
    expect(result.difference).toBeNull();
  });

  it('tolerates float drift across many rows without inventing a discrepancy', () => {
    const rows = Array.from({ length: 300 }, () =>
      transactionRow('ItemPrice', 'Principal', '0.10')
    );
    const text = [
      SETTLEMENT_HEADER,
      '90210\t2026-07-01\t2026-07-15\t2026-07-17\t30.00\tUSD\t\t\t\t\t\t\t\t\t\t',
      ...rows,
    ].join('\n');

    const [result] = reconcileSettlements(parse(text));
    expect(result.balanced).toBe(true);
  });

  it('reconciles each settlement separately when rows are combined', () => {
    const results = reconcileSettlements([
      ...parse(FILE_ONE),
      ...parse(FILE_TWO),
    ]);
    expect(results.map((entry) => entry.settlementId).sort()).toEqual([
      '90210',
      '90211',
    ]);
  });
});

describe('pass-through marketplace facilitator tax', () => {
  // Both legs of the same tax: collected from the buyer, withheld by Amazon.
  const TAX_PAIR = [
    transactionRow('ItemPrice', 'Principal', '25.99'),
    transactionRow('ItemPrice', 'Tax', '2.14'),
    transactionRow(
      'ItemWithheldTax',
      'MarketplaceFacilitatorTax-Principal',
      '-2.14'
    ),
    transactionRow('ItemPrice', 'GiftWrap', '3.99'),
    transactionRow('ItemPrice', 'GiftWrapTax', '0.28'),
    transactionRow(
      'ItemWithheldTax',
      'MarketplaceFacilitatorTax-Other',
      '-0.28'
    ),
    // The leg an allowlist of ("Tax", "GiftWrapTax") missed on real data.
    transactionRow('ItemPrice', 'Shipping', '1.49'),
    transactionRow('ItemPrice', 'ShippingTax', '0.12'),
    transactionRow(
      'ItemWithheldTax',
      'MarketplaceFacilitatorTax-Shipping',
      '-0.12'
    ),
  ];

  it('excludes both legs, and keeps everything else', () => {
    // No totals row: this is about the filter, and its empty columns would
    // only add a row with no description to compare against.
    const rows = parse([SETTLEMENT_HEADER, ...TAX_PAIR].join('\n'));
    const kept = economicRows(rows).map((row) => row.fields.amountDescription);
    expect(kept).toEqual(['Principal', 'GiftWrap', 'Shipping']);
  });

  it('reports a zero residual when both legs of every pair are recognised', () => {
    const rows = parse([SETTLEMENT_HEADER, ...TAX_PAIR].join('\n'));
    expect(passThroughTaxResidual(rows)).toBe(0);
  });

  it('surfaces a residual when a collected leg goes unrecognised', () => {
    // Simulates the next tax variant Amazon invents: withheld, but named so
    // that the collected side is not matched. Without this check the amount
    // silently becomes revenue.
    const rows = parse(
      [
        SETTLEMENT_HEADER,
        transactionRow('ItemPrice', 'SomeNewLevy', '0.50'),
        transactionRow(
          'ItemWithheldTax',
          'MarketplaceFacilitatorTax-New',
          '-0.50'
        ),
      ].join('\n')
    );
    expect(passThroughTaxResidual(rows)).toBe(-0.5);
  });

  it('drops exactly zero from the total, since the legs cancel', () => {
    // No totals row: this is about the filter, and its empty columns would
    // only add a row with no description to compare against.
    const rows = parse([SETTLEMENT_HEADER, ...TAX_PAIR].join('\n'));
    const sum = (list: typeof rows) =>
      Math.round(
        list.reduce((total, row) => total + (row.numbers?.amount ?? 0), 0) * 100
      ) / 100;

    // The whole point: excluding tax changes the revenue reading but not the
    // money. If these ever diverge, the filter is dropping something real.
    expect(sum(rows)).toBe(31.47);
    expect(sum(economicRows(rows))).toBe(31.47);
  });

  it('keeps a fee that merely mentions tax in its description', () => {
    const rows = parse(
      [
        SETTLEMENT_HEADER,
        TOTALS_ROW,
        transactionRow('ItemFees', 'Commission', '-3.90'),
      ].join('\n')
    );
    expect(isPassThroughTax(rows[0])).toBe(false);
  });
});

describe('Grade and Resell SKUs', () => {
  const KNOWN = [
    'NMS-FB-350-DW',
    'NMS-FB-350-BEI',
    'PCM-FB-15OZ-BLK-101',
    'FB-LFP-WHT-1600-100',
    'FB-LFP-BLK-1600-100',
    'TIF-FB-450-GLS',
  ];

  it('treats an ordinary SKU as its own parent, in new condition', () => {
    expect(resolveSku('PCM-FB-15OZ-BLK-101', KNOWN)).toEqual({
      sku: 'PCM-FB-15OZ-BLK-101',
      parentSku: 'PCM-FB-15OZ-BLK-101',
      condition: 'new',
      graded: false,
    });
  });

  it('reads the parent and the grade off a graded SKU', () => {
    expect(
      resolveSku('amzn.gr.TIF-FB-450-GLS-_ltRVX5UefTK48-LN', KNOWN)
    ).toEqual({
      sku: 'amzn.gr.TIF-FB-450-GLS-_ltRVX5UefTK48-LN',
      parentSku: 'TIF-FB-450-GLS',
      condition: 'LN',
      graded: true,
    });
  });

  it.each([
    // The cases a hyphen-splitting regex gets wrong: the opaque token contains
    // hyphens of its own, so nothing in the string marks where the parent ends.
    ['amzn.gr.NMS-FB-350-DW-AIuLag-pWeg3K10-LN', 'NMS-FB-350-DW', 'LN'],
    ['amzn.gr.NMS-FB-350-DW-d3Pd1d-1Z9NfB01-VG', 'NMS-FB-350-DW', 'VG'],
    // Token ending in a hyphen, so the SKU carries a double hyphen.
    ['amzn.gr.PCM-FB-15OZ-BLK-101-XhNNbefI--LN', 'PCM-FB-15OZ-BLK-101', 'LN'],
    // Token starting with a hyphen.
    ['amzn.gr.FB-LFP-BLK-1600-100--SHn8bakm-LN', 'FB-LFP-BLK-1600-100', 'LN'],
    // Grades other than Like New.
    ['amzn.gr.PCM-FB-15OZ-BLK-101-pQnN4U3e7-GD', 'PCM-FB-15OZ-BLK-101', 'GD'],
    ['amzn.gr.TIF-FB-450-GLS-1uzTpMPP8cWzHB-PO', 'TIF-FB-450-GLS', 'PO'],
  ])('resolves %s', (sku, parentSku, condition) => {
    const resolved = resolveSku(sku, KNOWN);
    expect(resolved.parentSku).toBe(parentSku);
    expect(resolved.condition).toBe(condition);
  });

  it('prefers the longest matching parent', () => {
    // WHT and BLK share no prefix, but a shorter SKU that prefixed a longer one
    // would otherwise win on iteration order alone.
    expect(
      resolveSku('amzn.gr.FB-LFP-WHT-1600-100-1rr5Ac2xv-VG', [
        ...KNOWN,
        'FB-LFP',
      ]).parentSku
    ).toBe('FB-LFP-WHT-1600-100');
  });

  it('does not treat a shorter SKU as a parent without a separator', () => {
    // NMS-FB-350-BE must not claim a NMS-FB-350-BEI unit.
    expect(
      resolveSku('amzn.gr.NMS-FB-350-BEI-G9cYCswCGlNPDS-LN', ['NMS-FB-350-BE'])
        .parentSku
    ).toBeNull();
  });

  it('returns null rather than guessing when the parent is unknown', () => {
    const resolved = resolveSku('amzn.gr.SOME-UNSEEN-SKU-abc123def-VG', KNOWN);
    expect(resolved.parentSku).toBeNull();
    expect(resolved.condition).toBe('VG');
    expect(resolved.graded).toBe(true);
  });

  it('collects only new-condition SKUs as the match set', () => {
    const rows = parse(
      [
        SETTLEMENT_HEADER,
        TOTALS_ROW,
        transactionRow(
          'ItemPrice',
          'Principal',
          '22.99',
          'PCM-FB-15OZ-BLK-101'
        ),
        transactionRow(
          'ItemPrice',
          'Principal',
          '20.69',
          'amzn.gr.PCM-FB-15OZ-BLK-101-HRsEIPd3N-LN'
        ),
      ].join('\n')
    );
    expect([...collectKnownSkus(rows)]).toEqual(['PCM-FB-15OZ-BLK-101']);
  });
});
